export enum Path {
  Home = "/",
  Stacks = "/stacks",
  Button = "/button",
  GridTable = "/grid-table",
  Modal = "/modal",
  TextInput = "/text-input",
  Select = "/select",
  SizeAware = "/size-aware",
  Colors = "/colors",
  Images = "/images",
  SelectView = "/select-view",
  Slider = "/slider",
  InfiniteScroll = "/infinite-scroll",
  Combobox = "/combobox",
  DistributionBar = "/distribution-bar",
  PieChart = "/piechart",
  DynamicForm = "/dynamic-form",
  Countdown = "/countdown",
  Nfts = "/nfts",
  IPFS = "/ipfs",
  Panel = "/panel",
  CalendarEditor = "/calendar-editor",
  TimeEditor = "/time-editor",
  Resume = "/resume",
}
