export enum Path {
  Home = "/",
  Stacks = "/stacks",
  Button = "/button",
  GridTable = "/grid-table",
  Modal = "/modal",
  TextInput = "/text-input",
  Select = "/select",
  SizeAware = "/size-aware",
  Colors = "/colors",
  Images = "/images",
  SelectView = "/select-view",
  InfiniteScroll = "/infinite-scroll",
  Combobox = "/combobox",
  DynamicForm = "/dynamic-form",
  Countdown = "/countdown",
  Nfts = "/nfts",
  IPFS = "/ipfs",
}
