// This file is generated by @radzionkit/ui/country/codegen/generateFlags.ts
import { SvgIconProps } from '@radzionkit/ui/icons/SvgIconProps'

const NlFlag = (props: SvgIconProps) => (
  <svg
    width="1em"
    height="0.75em"
    xmlns="http://www.w3.org/2000/svg"
    id="flag-icons-nl"
    viewBox="0 0 640 480"
    {...props}
  >
    <path fill="#21468b" d="M0 0h640v480H0z" />
    <path fill="#fff" d="M0 0h640v320H0z" />
    <path fill="#ae1c28" d="M0 0h640v160H0z" />
  </svg>
)

export default NlFlag
