import fs from 'fs'
import { format, resolveConfig } from 'prettier'
import path from 'path'

interface CreateTsFileParams {
  extension?: 'ts' | 'tsx'
  directory: string
  fileName: string
  generatedBy: string
  content: string
}

export const createTsFile = async ({
  extension = 'ts',
  directory,
  fileName,
  generatedBy,
  content,
}: CreateTsFileParams) => {
  fs.mkdirSync(directory, { recursive: true })

  const configPath = path.resolve(__dirname, '../../.prettierrc')

  const config = await resolveConfig(configPath)

  const formattedContent = await format(
    [`// This file is generated by ${generatedBy}`, content].join('\n'),
    {
      ...config,
      parser: 'typescript',
    },
  )

  const tsFilePath = `${directory}/${fileName}.${extension}`

  fs.writeFileSync(tsFilePath, formattedContent)
}
