// This file is generated by @lib/ui/country/codegen/generateFlags.ts
import { SvgProps } from '@lib/ui/props'

const HnFlag = (props: SvgProps) => (
  <svg
    width="1em"
    height="0.75em"
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    id="flag-icons-hn"
    viewBox="0 0 640 480"
    {...props}
  >
    <path fill="#18c3df" d="M0 0h640v480H0z" />
    <path fill="#fff" d="M0 160h640v160H0z" />
    <g id="hn-c" fill="#18c3df" transform="translate(320 240) scale(26.66665)">
      <g id="hn-b">
        <path id="hn-a" d="m-.3 0 .5.1L0-1z" />
        <use xlinkHref="#hn-a" transform="scale(-1 1)" />
      </g>
      <use xlinkHref="#hn-b" transform="rotate(72)" />
      <use xlinkHref="#hn-b" transform="rotate(-72)" />
      <use xlinkHref="#hn-b" transform="rotate(144)" />
      <use xlinkHref="#hn-b" transform="rotate(-144)" />
    </g>
    <use xlinkHref="#hn-c" transform="translate(133.3 -42.7)" />
    <use xlinkHref="#hn-c" transform="translate(133.3 37.3)" />
    <use xlinkHref="#hn-c" transform="translate(-133.3 -42.7)" />
    <use xlinkHref="#hn-c" transform="translate(-133.3 37.3)" />
  </svg>
)

export default HnFlag
